### ISSUE TITLE
go get not working

### ISSUE THREAD

**Issue by R4wm** [stratoberry/go-gpsd#16]
$ go get github.com/stratoberry/go-gpsd
go: github.com/stratoberry/go-gpsd: invalid github.com import path "github.com/stratoberry"

**Comment by josip** [comment]
Hi @R4wm, I've tried it on a brand new machine and it worked perfectly fine. The package wasn't unpublished and the docs are correctly [indexed on go.dev](https://pkg.go.dev/github.com/stratoberry/go-gpsd). 

Things I can suggest to try:

1) Verify you have the correct import line.
```go
// ...
import (
      "github.com/stratoberry/go-gpsd"
)
// ..
```
2) Test connectivity on your machine to Github.
3) Try importing another Go module in your project and see what happes.
