### ISSUE TITLE
go get github.com/stratoberry/go-gpsd returns an error

### ISSUE THREAD

**Issue by larsth** [stratoberry/go-gpsd#2]
IIf I type:

```
go get github.com/stratoberry/go-gpsd
```

then the following compiler error is shown (with the GOPATH part of the path replaced by $GOPATH by me):

```
# $GOPATH/src/github.com/stratoberry/go-gpsd/gpsd.go:170: line declared and not used
```

'line' is an unused variable in the Dial function.

**Comment by Sypheos** [comment]
Hello,

Pull the repository with
`go get -d github.com/stratoberry/go-gpsd`

Open gpsd.go and comment line 170. Close. Then

`go install github.com/stratoberry/go-gpsd/`

**Comment by foonix** [comment]
@josip Can you look at merging #3 ?

Let me know if there is anything I can do to help out.
