### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by marcelbuesing** [stratoberry/go-gpsd#5]
I can not find the license terms anywhere. Would you mind adding a License file ?

**Comment by icholy** [comment]
Also just noticed the blank license section in the README.

**Comment by batthebee** [comment]
Thanks for the good work! Please add license information so that we can fork and develop the project if necessary.

**Comment by josip** [comment]
Hi @marcelbuesing, @icholy, @batthebee thank you for raising this issue - I've added the MIT License to the repository.
